= C++ example project scanned on SonarCloud using GitHub Actions
// URIs:
:uri-qg-status: https://sonarcloud.io/dashboard?id=sc-sq-c-family-examples_linux-cmake-gh-actions-sc
:img-qg-status: https://sonarcloud.io/api/project_badges/measure?project=sc-sq-c-family-examples_linux-cmake-gh-actions-sc&metric=alert_status

image:{img-qg-status}[Quality Gate Status,link={uri-qg-status}]

*This project is analysed on https://sonarcloud.io/dashboard?id=sc-sq-c-family-examples_linux-cmake-gh-actions-sc[SonarCloud]!*

It is very easy to analyze a C/C++/Objective-C project with SonarCloud:

. Create a `sonar-project.properties` file to store your configuration
. In your `.github/workflows/build.yml` file:
.. Download the https://docs.sonarqube.org/latest/analysis/scan/sonarscanner/[Sonar Scanner]
.. Download the https://docs.sonarqube.org/latest/analysis/languages/cfamily/#header-4[Build Wrapper]
.. Wrap your compilation with the Build Wrapper
.. Run `sonar-scanner` as the final step

You can take a look at the link:sonar-project.properties[sonar-project.properties] and link:.github/workflows/build.yml[build.yml] to see it in practice.

= Documentation

- https://docs.sonarqube.org/latest/analysis/languages/cfamily/[Documentation of the C/C++/Objective-C plugin and its Build Wrapper]

= Linux\CMake

A build of the https://github.com/sc-sq-c-family-examples/code[code repository] on a Linux platform using CMake build system.

= Code Description

An example of a flawed C++ code. The https://github.com/sc-sq-c-family-examples/code[code repository] is meant to be compiled with different build systems using different CI pipelines on Linux, MacOS, and Windows.

The https://github.com/sc-sq-c-family-examples/code[code repository] is forked into other repositories in https://github.com/sc-sq-c-family-examples[this collection] to add a specific build system, platform, and CI.
The downstream repositories are analyzed either with https://www.sonarqube.org/[SonarQube] or https://sonarcloud.io/[SonarCloud].

== Forking the code repository
Since GitHub disallows forking of a repository within the same organization, here is the equivalent in `git` commands (on the example of `linux-cmake-gh-actions`):

Clone the newly created repository:
----
git clone gh:sc-sq-c-family-examples/linux-cmake-gh-actions
cd linux-cmake-gh-actions
----
Add the https://github.com/sc-sq-c-family-examples/code[code repository] as a second remote named `code`:
----
git remote add code git@github.com:sc-sq-c-family-examples/code
----
Get the code:
----
git pull code master
----
If the contents of the https://github.com/sc-sq-c-family-examples/code[code repository] changes, you can pull the changes with the last command.

Push the changes to the custom repository:
----
git push origin master
----
