= C++ example project scanned on SonarCloud using GitHub Actions
// URIs:
:uri-qg-status: https://sonarcloud.io/dashboard?id=sc-sq-c-family-examples_linux-cmake-gh-actions-sc
:img-qg-status: https://sonarcloud.io/api/project_badges/measure?project=sc-sq-c-family-examples_linux-cmake-gh-actions-sc&metric=alert_status

image:{img-qg-status}[Quality Gate Status,link={uri-qg-status}]

*This project is analysed on https://sonarcloud.io/dashboard?id=sc-sq-c-family-examples_linux-cmake-gh-actions-sc[SonarCloud]!*

It is very easy to analyze a C/C++/Objective-C project with SonarCloud:

. Create a `sonar-project.properties` file to store your configuration
. In your `.github/workflows/build.yml` file:
.. Download the https://docs.sonarqube.org/latest/analysis/scan/sonarscanner/[Sonar Scanner]
.. Download the https://docs.sonarqube.org/latest/analysis/languages/cfamily/#header-4[Build Wrapper]
.. Wrap your compilation with the Build Wrapper
.. Run `sonar-scanner` as the final step

You can take a look at the link:sonar-project.properties[sonar-project.properties] and link:.github/workflows/build.yml[build.yml] to see it in practice.

= Documentation

- https://docs.sonarqube.org/latest/analysis/languages/cfamily/[Documentation of the C/C++/Objective-C plugin and its Build Wrapper]

= Linux\CMake

A build of the https://github.com/sc-sq-c-family-examples/code[code repository] on a Linux platform using CMake build system.

To build the code run:
----
mkdir build && cd build
cmake ..
make
----

= Code Description

An example of a flawed C++ code. The https://github.com/sc-sq-c-family-examples/code[code repository] is meant to be compiled with different build systems using different CI pipelines on Linux, MacOS, and Windows.

The https://github.com/sc-sq-c-family-examples/code[code repository] is forked into other repositories in https://github.com/sc-sq-c-family-examples[this collection] to add a specific build system, platform, and CI.
The downstream repositories are analyzed either with https://www.sonarqube.org/[SonarQube] or https://sonarcloud.io/[SonarCloud].

You can find examples for:

* https://github.com/sc-sq-c-family-examples?q=linux[Linux]
* https://github.com/sc-sq-c-family-examples?q=macos[MacOS]
* https://github.com/sc-sq-c-family-examples?q=windows[Windows]

Using the following build systems:

* https://github.com/sc-sq-c-family-examples?q=cmake[CMake]
* https://github.com/sc-sq-c-family-examples?q=autotools[GNU Autotools]
* https://github.com/sc-sq-c-family-examples?q=xcode[Xcode]
* https://github.com/sc-sq-c-family-examples?q=msbuild[MSBuild]

Running on the following CI services:

* https://github.com/sc-sq-c-family-examples?q=azure[Azure DevOps]
* https://github.com/sc-sq-c-family-examples?q=gh-actions[GitHub Actions]
* https://github.com/sc-sq-c-family-examples?q=travis[Travis]
* https://github.com/sc-sq-c-family-examples?q=jenkins[Jenkins]
* https://github.com/sc-sq-c-family-examples?q=gitlab[GitLab CI]
* https://github.com/sc-sq-c-family-examples?q=bitbucket[BitBucket Pipelines]

Configured for analysis on:

* https://github.com/sc-sq-c-family-examples?q=-sq[SonarQube]
* https://github.com/sc-sq-c-family-examples?q=-sc[SonarCloud]


See link:./examples-structure.adoc[examples-structure.adoc] for a description of the structure of https://github.com/sc-sq-c-family-examples[this GitHub organization] and the relations between its different repositories.
